// Predefined exercise library with detailed information
export const exerciseLibrary = {
  chest: [
    {
      name: 'Push-Ups',
      equipment: 'None',
      level: ['Beginner', 'Intermediate', 'Advanced'],
      type: ['Bodyweight exercises', 'Weight training'],
      duration: '5 minutes',
      defaultSets: '3',
      defaultReps: '8-12',
    },
    {
      name: 'Dumbbell Bench Press',
      equipment: 'Dumbbells',
      level: ['Beginner', 'Intermediate', 'Advanced'],
      type: ['Weight training'],
      duration: '5 minutes',
      defaultSets: '3',
      defaultReps: '8-12',
    },
  ],
  back: [
    {
      name: 'Dumbbell Rows',
      equipment: 'Dumbbells',
      level: ['Beginner', 'Intermediate', 'Advanced'],
      type: ['Weight training'],
      duration: '5 minutes',
      defaultSets: '3',
      defaultReps: '8-12',
    },
    {
      name: 'Pull-Ups',
      equipment: 'Pull-up Bar',
      level: ['Intermediate', 'Advanced'],
      type: ['Bodyweight exercises', 'Weight training'],
      duration: '5 minutes',
      defaultSets: '3',
      defaultReps: '5-8',
    },
  ],
  legs: [
    {
      name: 'Bodyweight Squats',
      equipment: 'None',
      level: ['Beginner', 'Intermediate', 'Advanced'],
      type: ['Bodyweight exercises', 'Weight training'],
      duration: '5 minutes',
      defaultSets: '3',
      defaultReps: '12-15',
    },
    {
      name: 'Lunges',
      equipment: 'None',
      level: ['Beginner', 'Intermediate', 'Advanced'],
      type: ['Bodyweight exercises', 'Weight training'],
      duration: '5 minutes',
      defaultSets: '3',
      defaultReps: '10-12 per leg',
    },
  ],
  shoulders: [
    {
      name: 'Dumbbell Shoulder Press',
      equipment: 'Dumbbells',
      level: ['Beginner', 'Intermediate', 'Advanced'],
      type: ['Weight training'],
      duration: '5 minutes',
      defaultSets: '3',
      defaultReps: '8-12',
    },
    {
      name: 'Pike Push-Ups',
      equipment: 'None',
      level: ['Intermediate', 'Advanced'],
      type: ['Bodyweight exercises'],
      duration: '5 minutes',
      defaultSets: '3',
      defaultReps: '8-12',
    },
  ],
  core: [
    {
      name: 'Plank',
      equipment: 'None',
      level: ['Beginner', 'Intermediate', 'Advanced'],
      type: ['Bodyweight exercises'],
      duration: '5 minutes',
      defaultSets: '3',
      defaultReps: '30-60 seconds',
    },
    {
      name: 'Mountain Climbers',
      equipment: 'None',
      level: ['Beginner', 'Intermediate', 'Advanced'],
      type: ['Bodyweight exercises', 'HIIT'],
      duration: '5 minutes',
      defaultSets: '3',
      defaultReps: '20 per leg',
    },
  ],
  cardio: [
    {
      name: 'Burpees',
      equipment: 'None',
      level: ['Intermediate', 'Advanced'],
      type: ['Cardio', 'HIIT'],
      duration: '5 minutes',
      defaultSets: '3',
      defaultReps: '10',
    },
    {
      name: 'Jump Rope',
      equipment: 'Jump Rope',
      level: ['Beginner', 'Intermediate', 'Advanced'],
      type: ['Cardio'],
      duration: '5 minutes',
      defaultSets: '3',
      defaultReps: '50 jumps',
    },
  ],
  flexibility: [
    {
      name: 'Sun Salutation',
      equipment: 'Yoga Mat',
      level: ['Beginner', 'Intermediate', 'Advanced'],
      type: ['Yoga'],
      duration: '5 minutes',
      defaultSets: '3',
      defaultReps: '1 flow',
    },
    {
      name: 'Dynamic Stretching',
      equipment: 'None',
      level: ['Beginner', 'Intermediate', 'Advanced'],
      type: ['Yoga', 'Pilates'],
      duration: '5 minutes',
      defaultSets: '2',
      defaultReps: '10 per stretch',
    },
  ],
};

// Workout split templates based on days per week
export const workoutSplits = {
  3: [
    ['chest', 'shoulders', 'core'],
    ['back', 'legs', 'core'],
    ['shoulders', 'cardio', 'flexibility'],
  ],
  4: [
    ['chest', 'shoulders'],
    ['back', 'core'],
    ['legs', 'cardio'],
    ['shoulders', 'flexibility'],
  ],
  5: [
    ['chest', 'core'],
    ['back'],
    ['legs'],
    ['shoulders', 'core'],
    ['cardio', 'flexibility'],
  ],
  6: [
    ['chest'],
    ['back'],
    ['legs'],
    ['shoulders'],
    ['core', 'cardio'],
    ['flexibility'],
  ],
};